apiVersion: apps/v1
kind: Deployment
metadata:
  name: mssql-deployment
  namespace: location-dev
  labels:
    app: mssql
    component: database
    environment: development
    version: "2022-cu8"
  annotations:
    description: "SQL Server 2022 Developer Edition for Location development with extended ASCII support"
    created-by: "setup-dev.sh"
    deployment.kubernetes.io/revision: "1"
spec:
  replicas: 1
  strategy:
    type: Recreate  # SQL Server doesn't support rolling updates with persistent storage
  selector:
    matchLabels:
      app: mssql
      component: database
  template:
    metadata:
      labels:
        app: mssql
        component: database
        environment: development
    spec:
      containers:
      - name: mssql
        image: mcr.microsoft.com/mssql/server:2022-CU8-ubuntu-20.04
        imagePullPolicy: IfNotPresent
        env:
        - name: ACCEPT_EULA
          value: "Y"
        - name: MSSQL_PID
          value: "Developer"
        - name: SA_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mssql-secret
              key: SA_PASSWORD
        # Extended ASCII support configuration
        - name: MSSQL_COLLATION
          value: "SQL_Latin1_General_CP1252_CI_AS"
        - name: MSSQL_LCID
          value: "1033"
        - name: MSSQL_DATA_DIR
          value: "/var/opt/mssql/data"
        - name: MSSQL_LOG_DIR
          value: "/var/opt/mssql/data"
        - name: MSSQL_BACKUP_DIR
          value: "/var/opt/mssql/data"
        ports:
        - name: mssql
          containerPort: 1433
          protocol: TCP
        volumeMounts:
        - name: mssql-data
          mountPath: /var/opt/mssql/data
        resources:
          requests:
            memory: "2Gi"
            cpu: "500m"
          limits:
            memory: "4Gi"
            cpu: "2000m"
        livenessProbe:
          exec:
            command:
            - /opt/mssql-tools/bin/sqlcmd
            - -S
            - localhost
            - -U
            - sa
            - -P
            - $(SA_PASSWORD)
            - -Q
            - "SELECT 1"
          initialDelaySeconds: 60
          periodSeconds: 30
          timeo